# serverless.privileged.yaml

resources:
  Resources:
    DeployOrgRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${sls:stage}-org-stack-deployer-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: org-stack-deploy-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - cloudformation:CreateStack
                  Resource:
                    - arn:aws:cloudformation:*:*:stack/${sls:stage}-org-*/*
                - Effect: Allow
                  Action:
                    - dynamodb:CreateTable
                    - dynamodb:DescribeTable
                    - dynamodb:TagResource 
                    - dynamodb:UpdateContinuousBackups
                  Resource:
                    - arn:aws:dynamodb:eu-west-1:*:table/${sls:stage}-*
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:*:*:*
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:GetObject
                    - s3:ListBucket
                  Resource: 
                    - "arn:aws:s3:::${self:custom.config_bucket}"
                    - "arn:aws:s3:::${self:custom.config_bucket}/*"
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                    - dynamodb:GetItem
                    - dynamodb:DescribeContinuousBackups
                  Resource: 
                    - "arn:aws:dynamodb:eu-west-1:*:table/${self:custom.core_table_name}"
                    - "arn:aws:dynamodb:eu-west-1:*:table/${self:custom.core_table_name}/*"
                    - "arn:aws:dynamodb:eu-west-1:*:table/${sls:stage}-org-*"
                    - "arn:aws:dynamodb:eu-west-1:*:table/${sls:stage}-org-*/*"
        Tags:
          - Key: DanceEngineVersion
            Value: v2