# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-04-15T22:50:05+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, RootModel


class LocationObject(BaseModel):
    name: Optional[str] = None
    address: Optional[str] = None
    lat: Optional[float] = None
    lng: Optional[float] = None
    ksuid: Optional[str] = None


class EventObject(BaseModel):
    ksuid: Optional[str] = None
    banner: Optional[str] = None
    event_slug: Optional[str] = None
    organisation: Optional[str] = None
    type: Optional[str] = None
    name: Optional[str] = None
    starts_at: Optional[datetime] = None
    ends_at: Optional[datetime] = None
    category: Optional[List[str]] = None
    capacity: Optional[int] = None
    number_sold: Optional[int] = None
    description: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    location: Optional[LocationObject] = None


class CreateEventRequest(BaseModel):
    name: str
    starts_at: datetime
    ends_at: datetime
    banner: Optional[str] = None
    category: Optional[List[str]] = None
    capacity: int
    description: Optional[str] = None
    location: LocationObject


class EventResponse(BaseModel):
    message: Optional[str] = None
    event: Optional[EventObject] = None


class EventListResponse(RootModel[List[EventObject]]):
    root: List[EventObject]
