import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "core/dance-engine-api",
    },
    {
      type: "category",
      label: "Email",
      items: [
        {
          type: "doc",
          id: "core/email",
          label: "Send Tickets",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Tickets",
      items: [
        {
          type: "doc",
          id: "core/tickets",
          label: "Get All Tickets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/tickets-9301-e-109-7988-4-d-8-e-be-0-f-51-cf-80-d-16099",
          label: "Get Single Ticket",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Checkout",
      items: [
        {
          type: "doc",
          id: "core/checkout",
          label: "POST Checkout",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Bundles",
      items: [
        {
          type: "doc",
          id: "core/bundles",
          label: "Get All Bundles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/bundles-8-ccbc-3-f-0-b-6-f-8-4-fb-8-8-f-26-66026-b-2-a-1287",
          label: "Create Bundles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/bundles-eefab-071-15-f-3-4581-b-0-f-4-ea-1679319-ef-5",
          label: "Update Bundles",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/bundles-afd-5-e-2-b-1-985-e-4446-860-c-b-31-f-93663-ec-4",
          label: "Get Single Bundle",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/bundles-5-bf-0-c-580-c-860-4751-9-f-0-c-f-0-cdc-69-c-99-d-0",
          label: "Publish Bundles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/bundles-1310-f-539-91-ec-449-e-ba-9-f-0-b-0-ef-1-ee-7-f-60",
          label: "Public Get Bundles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/bundles-7-b-2-a-4292-477-e-4-e-38-b-4-d-5-99-ece-020320-c",
          label: "Public Get All Bundles",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Public",
      items: [
        {
          type: "doc",
          id: "core/bundles-1310-f-539-91-ec-449-e-ba-9-f-0-b-0-ef-1-ee-7-f-60",
          label: "Public Get Bundles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/bundles-7-b-2-a-4292-477-e-4-e-38-b-4-d-5-99-ece-020320-c",
          label: "Public Get All Bundles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/items-ee-64-a-41-c-3586-493-f-88-fa-8837-fc-374-f-1-e",
          label: "Public Get Item",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/items-b-5-b-52-a-2-f-6706-4-b-7-d-baae-776-de-75-b-1-f-8-c",
          label: "Public Get All Items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/organisations-d-4821-d-72-ac-34-4-c-81-a-618-12-ce-976-fbd-1-a",
          label: "Public Get Organisations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/events-2-a-47657-c-483-b-4559-8-efd-3987-ddc-7-c-0-e-4",
          label: "Public Get Event",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/events-bf-412860-40-cb-44-aa-bb-3-d-c-797-bc-6-fcfb-1",
          label: "Public Get ALL Events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/organisation-f-7015-b-51-d-108-4656-b-7-dd-0-cd-350-bded-68",
          label: "Public Get Organisation Settings",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Items",
      items: [
        {
          type: "doc",
          id: "core/items",
          label: "Get All Items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/items-62-aa-9-fd-2-8982-485-d-87-f-2-08-fec-2635-db-2",
          label: "Create Item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/items-36-d-2-ec-9-c-3-cf-7-464-d-8-ac-8-a-42-c-43-e-0-c-938",
          label: "Update Items",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/items-29-dace-5-c-5369-4-d-30-894-b-f-39-bf-6248-c-14",
          label: "Get Single Item",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/items-30-d-55051-ced-0-483-e-91-e-0-8-fd-95-ebc-5-e-9-c",
          label: "Publish Items",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/items-ee-64-a-41-c-3586-493-f-88-fa-8837-fc-374-f-1-e",
          label: "Public Get Item",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/items-b-5-b-52-a-2-f-6706-4-b-7-d-baae-776-de-75-b-1-f-8-c",
          label: "Public Get All Items",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Organisations",
      items: [
        {
          type: "doc",
          id: "core/organisations",
          label: "GET organisations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/organisations-ae-1023-cd-5399-4133-bc-1-f-70-e-34-f-6-bd-546",
          label: "POST organisations",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/organisations-d-4821-d-72-ac-34-4-c-81-a-618-12-ce-976-fbd-1-a",
          label: "Public Get Organisations",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Event_Brdige",
      items: [
        {
          type: "doc",
          id: "core/eventbridge",
          label: "Trigger an event (org)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/eventbridge-fc-759-a-01-8-e-35-4-ee-2-8-ff-0-55-c-3-a-10-f-12-d-3",
          label: "Trigger an event",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Events",
      items: [
        {
          type: "doc",
          id: "core/events",
          label: "Get All Events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/events-d-9728-a-1-d-685-e-425-d-8239-cd-43-f-75-a-6258",
          label: "Create Event",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/events-fbd-32-ed-4-3507-493-f-85-a-1-615-ceabc-03-b-4",
          label: "Get Single Event",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/events-a-41-e-4770-4742-4369-8-d-68-e-602895-cdf-87",
          label: "Update an Event",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/events-2-a-449-c-58-6-eec-4-e-6-d-a-915-b-25-f-25104-e-3-a",
          label: "Delete an Event",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "core/events-2-a-47657-c-483-b-4559-8-efd-3987-ddc-7-c-0-e-4",
          label: "Public Get Event",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/events-bf-412860-40-cb-44-aa-bb-3-d-c-797-bc-6-fcfb-1",
          label: "Public Get ALL Events",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "S3",
      items: [
        {
          type: "doc",
          id: "core/presigned-url",
          label: "Generate Presigned Upload URL",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/presigned-url-1456-a-74-e-2-e-2-b-497-e-a-0-a-5-39-b-58-c-4-a-1-e-1-f",
          label: "Generate Presigned Download URL",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Customers",
      items: [
        {
          type: "doc",
          id: "core/customers",
          label: "Get All Customers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/customers-9-e-53-b-63-d-597-f-446-e-add-2-fe-9-ce-460-c-3-d-8",
          label: "Create Customer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "core/customers-0224-b-81-b-7-d-54-42-f-6-8639-b-01551-cac-939",
          label: "Get Single Customer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/customers-89725136-bf-05-4871-87-ec-ea-442-ccd-1433",
          label: "Update a Customer",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Organisation",
      items: [
        {
          type: "doc",
          id: "core/organisation",
          label: "Get Organisation Settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "core/organisation-0-ff-9057-a-210-d-4-c-48-94-d-5-5-df-899-e-56186",
          label: "Update Organisation Settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "core/organisation-f-7015-b-51-d-108-4656-b-7-dd-0-cd-350-bded-68",
          label: "Public Get Organisation Settings",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "core/schemas/locationobject",
          label: "LocationObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/eventobject",
          label: "EventObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/eventobjectpublic",
          label: "EventObjectPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/createeventrequest",
          label: "CreateEventRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/updateeventrequest",
          label: "UpdateEventRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/deleteeventrequest",
          label: "DeleteEventRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/eventresponse",
          label: "EventResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/eventlistresponse",
          label: "EventListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/eventresponsepublic",
          label: "EventResponsePublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/eventlistresponsepublic",
          label: "EventListResponsePublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/organisationobject",
          label: "OrganisationObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/organisationobjectpublic",
          label: "OrganisationObjectPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/organisationresponse",
          label: "OrganisationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/organisationresponsepublic",
          label: "OrganisationResponsePublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/updateorganisationrequest",
          label: "UpdateOrganisationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/organisationthemeobject",
          label: "OrganisationThemeObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/createorganisationrequest",
          label: "CreateOrganisationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/organisationslistresponse",
          label: "OrganisationsListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/organisationslistresponsepublic",
          label: "OrganisationsListResponsePublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/pricescheduleobject",
          label: "PriceScheduleObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/itemobject",
          label: "ItemObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/itemobjectpublic",
          label: "ItemObjectPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/createitemrequest",
          label: "CreateItemRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/publishitemsrequest",
          label: "PublishItemsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/updateitemrequest",
          label: "UpdateItemRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/itemresponse",
          label: "ItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/itemlistresponse",
          label: "ItemListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/itemresponsepublic",
          label: "ItemResponsePublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/itemlistresponsepublic",
          label: "ItemListResponsePublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/bundlepricescheduleobject",
          label: "BundlePriceScheduleObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/bundleobject",
          label: "BundleObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/bundleobjectpublic",
          label: "BundleObjectPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/createbundlerequest",
          label: "CreateBundleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/publishbundlesrequest",
          label: "PublishBundlesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/updatebundlerequest",
          label: "UpdateBundleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/bundleresponse",
          label: "BundleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/bundlelistresponse",
          label: "BundleListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/bundleresponsepublic",
          label: "BundleResponsePublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/bundlelistresponsepublic",
          label: "BundleListResponsePublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/lineitemobjectpublic",
          label: "LineItemObjectPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/checkoutobjectpublic",
          label: "CheckoutObjectPublic",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/createcheckoutrequest",
          label: "CreateCheckoutRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/customerobject",
          label: "CustomerObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/createcustomerrequest",
          label: "CreateCustomerRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/updatecustomerrequest",
          label: "UpdateCustomerRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/customerlistresponse",
          label: "CustomerListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/ticketobject",
          label: "TicketObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/ticketlistresponse",
          label: "TicketListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/sendticketemailrequest",
          label: "SendTicketEmailRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/errorresponse",
          label: "ErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/generatepresigneduploadrequest",
          label: "GeneratePresignedUploadRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/generatepresigneddownloadrequest",
          label: "GeneratePresignedDownloadRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/organisation",
          label: "organisation",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/event",
          label: "event",
          className: "schema",
        },
        {
          type: "doc",
          id: "core/schemas/ksuid",
          label: "ksuid",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
