# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-02-13T18:53:59+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, RootModel


class ErrorResponse(BaseModel):
    message: Optional[str] = None
    error: Optional[str] = None


class Action(Enum):
    post = 'POST'


class GeneratePresignedUploadRequest(BaseModel):
    action: Action = Field(
        ...,
        description='Action type. Must be `"POST"` for file upload.',
        examples=['POST'],
    )
    field_name: str = Field(
        ...,
        alias='fieldName',
        description='(used to generate S3 key path).',
        examples=[' '],
    )
    file_type: str = Field(
        ...,
        alias='fileType',
        description='MIME type of the file being uploaded.',
        examples=['image/jpeg'],
    )
    organisation: Optional[str] = Field(
        None,
        description='Organisation slug (usually injected from path parameter, but can also be set manually).',
        examples=['mlf'],
    )


class Action1(Enum):
    get = 'GET'


class GeneratePresignedDownloadRequest(BaseModel):
    action: Action1 = Field(
        ...,
        description='Action type. Must be `"GET"` for file download.',
        examples=['GET'],
    )
    file_key: str = Field(
        ...,
        alias='fileKey',
        description='S3 key for the file to download.',
        examples=[' '],
    )
    organisation: Optional[str] = Field(
        None,
        description='Organisation slug (optional, not directly used by the GET logic).',
        examples=['mlf'],
    )


class Organisation(RootModel[str]):
    root: str


class Event(Organisation):
    pass


class Ksuid(Organisation):
    pass
