# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-23T18:14:19+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, RootModel


class ErrorResponse(BaseModel):
    message: Optional[str] = None
    error: Optional[str] = None


class Action(Enum):
    post = 'POST'


class GeneratePresignedUploadRequest(BaseModel):
    action: Action = Field(
        ...,
        description='Action type. Must be `"POST"` for file upload.',
        examples=['POST'],
    )
    field_name: str = Field(
        ...,
        alias='fieldName',
        description='(used to generate S3 key path).',
        examples=[' '],
    )
    file_type: str = Field(
        ...,
        alias='fileType',
        description='MIME type of the file being uploaded.',
        examples=['image/jpeg'],
    )
    organisation: Optional[str] = Field(
        None,
        description='Organisation slug (usually injected from path parameter, but can also be set manually).',
        examples=['mlf'],
    )


class Action1(Enum):
    get = 'GET'


class GeneratePresignedDownloadRequest(BaseModel):
    action: Action1 = Field(
        ...,
        description='Action type. Must be `"GET"` for file download.',
        examples=['GET'],
    )
    file_key: str = Field(
        ...,
        alias='fileKey',
        description='S3 key for the file to download.',
        examples=[' '],
    )
    organisation: Optional[str] = Field(
        None,
        description='Organisation slug (optional, not directly used by the GET logic).',
        examples=['mlf'],
    )


class Mode(Enum):
    limited = 'limited'
    unlimited = 'unlimited'


class CapacityObject(BaseModel):
    mode: Optional[Mode] = 'unlimited'
    ksuid: Optional[str] = Field(None, description='ID of the object')
    parent_ksuid: Optional[str] = Field(
        None,
        description='ID of the parent object this capacity belongs to, e.g. an event or item or bundle',
    )
    capacity: Optional[int] = Field(
        None, description="Total capacity (only relevant if mode is 'limited')"
    )
    remaining_capacity: Optional[int] = Field(
        None, description="Remaining capacity (only relevant if mode is 'limited')"
    )
    reserved_capacity: Optional[int] = Field(
        None, description="Reserved capacity (only relevant if mode is 'limited')"
    )
    allocated_count: Optional[int] = Field(
        None,
        description="Number of this thing already allocated, probably through a sale (only relevant if mode is 'limited')",
    )
    version: Optional[int] = Field(None, description='Version number')
    oversell_limit: Optional[int] = Field(
        None,
        description="*Future Feature: Number of additional items that can be sold beyond the defined capacity (only relevant if mode is 'limited')",
    )


class Organisation(RootModel[str]):
    root: str


class Event(Organisation):
    pass


class Ksuid(Organisation):
    pass


class OrganisationId(Organisation):
    pass
