# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-02-25T15:02:34+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class BundlePriceScheduleObject(BaseModel):
    something: Optional[str] = None


class Status(Enum):
    draft = 'draft'
    live = 'live'
    archived = 'archived'
    outdated = 'outdated'


class BundleObject(BaseModel):
    ksuid: Optional[str] = None
    name: str
    description: Optional[str] = None
    status: Optional[Status] = None
    primary_price: Optional[float] = Field(
        None, description='Primary price of the bundle in pennies'
    )
    secondary_price: Optional[float] = Field(
        None, description='Secondary price of the bundle in pennies'
    )
    tertiary_price: Optional[float] = Field(
        None, description='Tertiary price of the bundle in pennies'
    )
    primary_price_name: Optional[str] = Field(None, description='Name of primary price')
    secondary_price_name: Optional[str] = Field(
        None, description='Name of secondary price'
    )
    tertiary_price_name: Optional[str] = Field(
        None, description='Name of tertiary price'
    )
    pricing_schedule: Optional[BundlePriceScheduleObject] = None
    stripe_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id'
    )
    stripe_primary_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id for the primary price'
    )
    stripe_secondary_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id for the secondary price'
    )
    stripe_tertiary_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id for the tertiary price'
    )
    stripe_product_id: Optional[str] = Field(
        None, description='Whats the related stripe product_id'
    )
    includes: Optional[List[str]] = None
    entity_type: Optional[str] = None


class BundleObjectPublic(BundleObject):
    pass


class CreateBundleRequest(BaseModel):
    bundles: List[BundleObject]


class UpdateBundleRequest(CreateBundleRequest):
    pass


class BundleResponse(BaseModel):
    bundle: Optional[BundleObject] = None


class BundleListResponse(BaseModel):
    bundles: Optional[List[BundleObject]] = None


class BundleResponsePublic(BaseModel):
    bundle: Optional[BundleObjectPublic] = None


class BundleListResponsePublic(BaseModel):
    bundles: Optional[List[BundleObjectPublic]] = None
