# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-02-10T23:30:40+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class LineItemObjectPublic(BaseModel):
    event_ksuid: Optional[str] = Field(
        None, description='The ksuid of the event associated with this item'
    )
    price_id: Optional[str] = Field(
        None, description='The price id of the product in stripe'
    )
    quantity: Optional[int] = Field(
        None, description='The quantity of this item to add to the checkout'
    )


class CheckoutObjectPublic(BaseModel):
    coupon_code: Optional[str] = Field(
        None, description='The coupon code to apply to the checkout'
    )
    success_url: str = Field(
        ..., description='The url to redirect to after a successful checkout'
    )
    cancel_url: str = Field(
        ..., description='The url to redirect to after a cancelled checkout'
    )
    application_fee_amount: Optional[int] = Field(
        None, description='The amount to charge as an application fee in cents'
    )
    stripe_account_id: str = Field(
        ..., description='The stripe account id to use for this checkout'
    )
    line_items: List[LineItemObjectPublic]


class CreateCheckoutRequest(BaseModel):
    checkout: List[CheckoutObjectPublic]
