# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-02-27T17:59:16+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class LineItemObjectPublic(BaseModel):
    ksuid: str = Field(
        ..., description='The ksuid of the item/bundle associated with this line item'
    )
    entity_type: str = Field(
        ..., description="The type of the line item, either 'item' or 'bundle'"
    )
    name: str = Field(
        ..., description='The name of the product associated with this line item'
    )
    includes: Optional[List[str]] = Field(
        None,
        description="The list of items included in this line item if it's a bundle",
    )
    event_ksuid: str = Field(
        ..., description='The ksuid of the event associated with this item'
    )
    price_id: str = Field(..., description='The price id of the product in stripe')
    quantity: Optional[int] = Field(
        1, description='The quantity of this item to add to the checkout'
    )


class CheckoutObjectPublic(BaseModel):
    email: Optional[str] = Field(
        None,
        description='The email of the customer to send the receipt to. Only applicable if collect_customer_on_stripe is false',
    )
    name: Optional[str] = Field(
        None,
        description='The name of the customer to send the receipt to. Only applicable if collect_customer_on_stripe is false',
    )
    collect_customer_on_stripe: Optional[bool] = Field(
        False,
        description='Whether to collect customer information on stripe during checkout',
    )
    coupon_code: Optional[str] = Field(
        None, description='The coupon code to apply to the checkout'
    )
    success_url: str = Field(
        ..., description='The url to redirect to after a successful checkout'
    )
    cancel_url: str = Field(
        ..., description='The url to redirect to after a cancelled checkout'
    )
    application_fee_amount: Optional[int] = Field(
        None, description='The amount to charge as an application fee in cents'
    )
    stripe_account_id: str = Field(
        ..., description='The stripe account id to use for this checkout'
    )
    line_items: List[LineItemObjectPublic]


class CreateCheckoutRequest(BaseModel):
    checkout: List[CheckoutObjectPublic]
