# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-01-22T21:07:16+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class LineItemObjectPublic(BaseModel):
    price_id: Optional[str] = Field(
        None, description='The price id of the product in stripe'
    )
    quantity: Optional[int] = Field(
        None, description='The quantity of this item to add to the checkout'
    )


class CheckoutObjectPublic(BaseModel):
    line_items: List[LineItemObjectPublic]


class CreateCheckoutRequest(BaseModel):
    checkout: List[CheckoutObjectPublic]
