# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-03-02T20:29:04+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class CustomerObject(BaseModel):
    ksuid: Optional[str] = Field(None, description='ID of the customer')
    name: str = Field(..., description='The name of the customer.')
    email: Optional[str] = Field(None, description='The email of the customer.')
    phone: Optional[str] = Field(None, description='Phone number for the customer.')
    bio: Optional[str] = Field(
        None, description='Short description or biography for the customer.'
    )
    tickets: Optional[List[Dict[str, Any]]] = Field(
        None, description='List of tickets associated with the customer.'
    )
    version: Optional[int] = None


class CreateCustomerRequest(BaseModel):
    customer: CustomerObject


class UpdateCustomerRequest(CreateCustomerRequest):
    pass


class CustomerListResponse(BaseModel):
    customers: Optional[List[CustomerObject]] = None
