# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-02-27T17:59:17+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class SendTicketEmailRequest(BaseModel):
    tickets: List[str]
