# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-02-24T21:38:05+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class PriceScheduleObject(BaseModel):
    something: Optional[str] = None


class Status(Enum):
    draft = 'draft'
    live = 'live'
    archived = 'archived'
    outdated = 'outdated'


class ItemObject(BaseModel):
    ksuid: Optional[str] = None
    name: str
    description: Optional[str] = None
    status: Optional[Status] = None
    column: Optional[float] = Field(None, description='??')
    row: Optional[float] = Field(None, description='??')
    primary_price: Optional[float] = Field(
        None, description='Primary price of the item in pennies'
    )
    secondary_price: Optional[float] = Field(
        None, description='Secondary price of the item in pennies'
    )
    tertiary_price: Optional[float] = Field(
        None, description='Tertiary price of the item in pennies'
    )
    primary_price_name: Optional[str] = Field(None, description='Name of primary price')
    secondary_price_name: Optional[str] = Field(
        None, description='Name of secondary price'
    )
    tertiary_price_name: Optional[str] = Field(
        None, description='Name of tertiary price'
    )
    individually_purchaseable: Optional[bool] = Field(
        None, description="Would you like people to purchase this on it's own"
    )
    stripe_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id'
    )
    stripe_primary_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id for the primary price'
    )
    stripe_secondary_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id for the secondary price'
    )
    stripe_tertiary_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id for the tertiary price'
    )
    stripe_product_id: Optional[str] = Field(
        None, description='Whats the related stripe product_id'
    )
    entity_type: Optional[str] = None
    pricing_schedule: Optional[PriceScheduleObject] = None


class ItemObjectPublic(BaseModel):
    ksuid: Optional[str] = None
    name: str
    description: Optional[str] = None
    status: Optional[Status] = None
    column: Optional[float] = Field(None, description='??')
    row: Optional[float] = Field(None, description='??')
    primary_price: Optional[float] = Field(
        None, description='Primary price of the item in pennies'
    )
    secondary_price: Optional[float] = Field(
        None, description='Secondary price of the item in pennies'
    )
    tertiary_price: Optional[float] = Field(
        None, description='Tertiary price of the item in pennies'
    )
    primary_price_name: Optional[str] = Field(None, description='Name of primary price')
    secondary_price_name: Optional[str] = Field(
        None, description='Name of secondary price'
    )
    tertiary_price_name: Optional[str] = Field(
        None, description='Name of tertiary price'
    )
    individually_purchaseable: Optional[bool] = Field(
        None, description="Would you like people to purchase this on it's own"
    )
    stripe_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id'
    )
    stripe_primary_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id for the primary price'
    )
    stripe_secondary_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id for the secondary price'
    )
    stripe_tertiary_price_id: Optional[str] = Field(
        None, description='Whats the related stripe price_id for the tertiary price'
    )
    stripe_product_id: Optional[str] = Field(
        None, description='Whats the related stripe product_id'
    )
    entity_type: Optional[str] = None


class CreateItemRequest(BaseModel):
    items: List[ItemObject]


class PublishItemsRequest(BaseModel):
    items: List[str] = Field(..., description='List of item KSUIDs to publish')


class UpdateItemRequest(CreateItemRequest):
    pass


class ItemResponse(BaseModel):
    item: Optional[ItemObject] = None


class ItemListResponse(BaseModel):
    items: Optional[List[ItemObject]] = None


class ItemResponsePublic(BaseModel):
    item: Optional[ItemObjectPublic] = None


class ItemListResponsePublic(BaseModel):
    items: Optional[List[ItemObjectPublic]] = None
