# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-02-23T12:44:37+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Status(Enum):
    i_am_teapot = 'i-am-teapot'
    draft = 'draft'
    active = 'active'
    setup = 'setup'
    suspended = 'suspended'
    archived = 'archived'


class OrganisationObject(BaseModel):
    status: Optional[Status] = 'draft'
    ksuid: Optional[str] = Field(None, description='ID of the organisation')
    organisation: Optional[str] = Field(
        None, description='Short slug used to represent the org'
    )
    name: str = Field(..., description='The name of the organisation.', min_length=2)
    account_id: Optional[str] = Field(
        None, description='The Stripe account ID associated with the organisation'
    )
    banner: Optional[str] = Field(
        None, description='URL to the banner image for the organisation'
    )
    banner_overlay: Optional[str] = Field(
        None, description='URL to the banner overlay image for the organisation'
    )
    logo: Optional[str] = Field(
        None, description='URL to the logo image for the organisation'
    )
    css_vars: Optional[str] = Field(
        None,
        description='CSS variables for the organisation used to customise SOLO templates',
    )
    description: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    version: Optional[int] = None
    history: Optional[List[Dict[str, Any]]] = None
    logo_secondary_url: Optional[str] = Field(
        None,
        description='Secondary URL to the logo image for the organisation, used for dark mode or alternative themes',
    )
    logo_icon_url: Optional[str] = Field(
        None,
        description='URL to the icon version of the logo for the organisation, used in places where a smaller or simplified logo is needed',
    )
    colour_primary: Optional[str] = Field(
        None,
        description='Primary colour for the organisation, used for theming and branding purposes',
    )
    colour_primary_dark: Optional[str] = Field(
        None,
        description='Darker shade of the primary colour for the organisation, used for hover states and accents',
    )
    colour_primary_light: Optional[str] = Field(
        None,
        description='Lighter shade of the primary colour for the organisation, used for backgrounds and highlights',
    )
    colour_secondary: Optional[str] = Field(
        None,
        description='Secondary colour for the organisation, used for theming and branding purposes',
    )
    colour_secondary_dark: Optional[str] = Field(
        None,
        description='Darker shade of the secondary colour for the organisation, used for hover states and accents',
    )
    colour_secondary_light: Optional[str] = Field(
        None,
        description='Lighter shade of the secondary colour for the organisation, used for backgrounds and highlights',
    )
    colour_background: Optional[str] = Field(
        None,
        description='Background colour for the organisation, used for theming and branding purposes',
    )
    colour_background_alt: Optional[str] = Field(
        None,
        description='Alternative background colour for the organisation, used for theming and branding purposes',
    )
    colour_text_primary: Optional[str] = Field(
        None,
        description='Text colour for the organisation, used for theming and branding purposes',
    )
    colour_text_secondary: Optional[str] = Field(
        None,
        description='Secondary text colour for the organisation, used for theming and branding purposes',
    )
    colour_text_inverted: Optional[str] = Field(
        None,
        description='Inverted text colour for the organisation, used for theming and branding purposes',
    )


class OrganisationResponse(BaseModel):
    organisation: Optional[OrganisationObject] = None


class UpdateOrganisationRequest(BaseModel):
    organisation: OrganisationObject


class OrganisationObjectPublic(BaseModel):
    organisation: Optional[str] = Field(
        None, description='Short slug used to represent the org'
    )
    name: str = Field(..., description='The name of the organisation.', min_length=2)
    account_id: Optional[str] = Field(
        None, description='The Stripe account ID associated with the organisation'
    )
    banner: Optional[str] = Field(
        None, description='URL to the banner image for the organisation'
    )
    banner_overlay: Optional[str] = Field(
        None, description='URL to the banner overlay image for the organisation'
    )
    logo: Optional[str] = Field(
        None, description='URL to the logo image for the organisation'
    )
    css_vars: Optional[str] = Field(
        None,
        description='CSS variables for the organisation used to customise SOLO templates',
    )
    description: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    version: Optional[int] = None


class CreateOrganisationRequest(UpdateOrganisationRequest):
    pass


class OrganisationsListResponse(BaseModel):
    organisations: Optional[List[OrganisationObject]] = None


class OrganisationsListResponsePublic(BaseModel):
    organisations: Optional[List[OrganisationObjectPublic]] = None
