# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-23T10:24:34+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Status(Enum):
    i_am_teapot = 'i-am-teapot'
    draft = 'draft'
    active = 'active'
    setup = 'setup'
    suspended = 'suspended'
    archived = 'archived'


class OrganisationThemeObject(BaseModel):
    css_vars: Optional[str] = Field(
        None,
        description='CSS variables for the organisation theme, used to customise SOLO templates',
    )
    colour_primary: Optional[str] = Field(
        None,
        description='Primary colour for the organisation theme, used for branding and UI accents',
    )
    colour_secondary: Optional[str] = Field(
        None,
        description='Secondary colour for the organisation theme, used for supporting accents',
    )
    colour_background: Optional[str] = Field(
        None, description='Background colour for the organisation theme'
    )
    colour_background_alt: Optional[str] = Field(
        None, description='Alternative background colour for the organisation theme'
    )
    colour_surface_light: Optional[str] = Field(
        None, description='Light surface colour for the organisation theme'
    )
    colour_surface_dark: Optional[str] = Field(
        None, description='Dark surface colour for the organisation theme'
    )


class ConfirmDeleteData(Enum):
    boolean_true = True


class DeleteOrganisationRequest(BaseModel):
    confirm_delete_data: ConfirmDeleteData
    confirm_stripe_managed_separately: ConfirmDeleteData
    confirm_irreversible: ConfirmDeleteData


class DeleteOrganisationResponse(BaseModel):
    message: Optional[str] = None
    organisation: Optional[str] = None
    stack_id: Optional[str] = Field(None, alias='stackId')
    offboarding: Optional[bool] = None
    archived: Optional[bool] = None


class OrganisationStackStatusResponse(BaseModel):
    organisation: Optional[str] = None
    stack_id: Optional[str] = Field(None, alias='stackId')
    stack_name: Optional[str] = Field(None, alias='stackName')
    stack_status: Optional[str] = Field(None, alias='stackStatus')
    pct: Optional[int] = None
    done: Optional[bool] = None
    ok: Optional[bool] = None
    archived: Optional[bool] = None
    touched_steps: Optional[int] = Field(None, alias='touchedSteps')
    total_steps: Optional[int] = Field(None, alias='totalSteps')


class OrganisationObject(BaseModel):
    status: Optional[Status] = 'draft'
    ksuid: Optional[str] = Field(None, description='ID of the organisation')
    organisation: Optional[str] = Field(
        None, description='Short slug used to represent the org'
    )
    name: str = Field(..., description='The name of the organisation.', min_length=2)
    account_id: Optional[str] = Field(
        None, description='The Stripe account ID associated with the organisation'
    )
    banner: Optional[str] = Field(
        None, description='URL to the banner image for the organisation'
    )
    banner_overlay: Optional[str] = Field(
        None, description='URL to the banner overlay image for the organisation'
    )
    logo: Optional[str] = Field(
        None, description='URL to the logo image for the organisation'
    )
    theme: Optional[OrganisationThemeObject] = None
    description: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    version: Optional[int] = None
    history: Optional[List[Dict[str, Any]]] = None
    logo_secondary_url: Optional[str] = Field(
        None,
        description='Secondary URL to the logo image for the organisation, used for dark mode or alternative themes',
    )
    logo_icon_url: Optional[str] = Field(
        None,
        description='URL to the icon version of the logo for the organisation, used in places where a smaller or simplified logo is needed',
    )
    whatsapp_join_url: Optional[str] = Field(
        None, description='Public WhatsApp join URL for approved members'
    )


class OrganisationObjectPublic(OrganisationObject):
    whatsapp_join_url: Optional[str] = Field(
        None, exclude=True, description='Hidden from public organisation responses'
    )


class OrganisationResponse(BaseModel):
    organisation: Optional[OrganisationObject] = None


class OrganisationResponsePublic(BaseModel):
    organisation: Optional[OrganisationObjectPublic] = None


class UpdateOrganisationRequest(BaseModel):
    organisation: OrganisationObject


class CreateOrganisationRequest(UpdateOrganisationRequest):
    pass


class OrganisationsListResponse(BaseModel):
    organisations: Optional[List[OrganisationObject]] = None


class OrganisationsListResponsePublic(BaseModel):
    organisations: Optional[List[OrganisationObjectPublic]] = None
