# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-11T18:53:18+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class TicketStatus(Enum):
    active = 'active'
    void = 'void'
    used = 'used'


class FinancialStatus(Enum):
    paid = 'paid'
    unpaid = 'unpaid'
    partially_refunded = 'partially_refunded'
    refunded = 'refunded'
    comp = 'comp'


class AdmissionStatus(Enum):
    checked_in = 'checked_in'
    not_checked_in = 'not_checked_in'
    denied = 'denied'


class TicketObject(BaseModel):
    ksuid: Optional[str] = Field(None, description='Unique identifier for the ticket')
    name: Optional[str] = Field(None, description='Name of the ticket')
    name_on_ticket: Optional[str] = Field(
        None, description='Name to be printed on the ticket'
    )
    customer_email: Optional[str] = Field(
        None, description='Email of the customer who owns the ticket'
    )
    created_at: Optional[datetime] = Field(
        None, description='Timestamp when the ticket was created'
    )
    updated_at: Optional[datetime] = Field(
        None, description='Timestamp when the ticket was last updated'
    )
    includes: Optional[List[str]] = Field(
        None, description='List of items included with the ticket'
    )
    expanded_includes: Optional[List[Dict[str, Any]]] = Field(
        None, description='List of the items included with the ticket'
    )
    ticket_status: Optional[TicketStatus] = Field(
        None, description='Status of the ticket'
    )
    financial_status: Optional[FinancialStatus] = Field(
        None, description='Financial status of the ticket'
    )
    admission_status: Optional[AdmissionStatus] = Field(
        'not_checked_in', description='Admission status of the ticket'
    )
    qr_token: Optional[str] = Field(None, description='QR token for the ticket')
    checked_in_at: Optional[datetime] = Field(
        None, description='Timestamp when the ticket was checked in'
    )
    checked_in_by: Optional[str] = Field(
        None, description='Identifier of the user who checked in the ticket'
    )
    check_in_count: Optional[int] = Field(
        None, description='Number of times the ticket has been checked in'
    )


class TicketListResponse(BaseModel):
    tickets: Optional[List[TicketObject]] = None


class SendTicketEmailRequest(BaseModel):
    tickets: List[str]


class LineItem(BaseModel):
    ksuid: str
    entity_type: str
    name: str
    includes: Optional[List[str]] = None


class Ticket(BaseModel):
    customer_email: str
    name_on_ticket: str
    ticket_creation_key: Optional[str] = None
    line_items: List[LineItem]


class BulkImportTicketsRequest(BaseModel):
    preview: Optional[bool] = Field(
        None,
        description='When true, return the tickets that would be created together with validation, conflict and duplicate information.',
    )
    parent_event_ksuid: Optional[str] = Field(
        None,
        description='KSUID of the parent event for which the tickets are being imported. This is required if the event has variations.',
    )
    tickets: List[Ticket]


class UpdateTicketRequest(BaseModel):
    ticket: TicketObject
