# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-09T20:34:00+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class TicketObject(BaseModel):
    ksuid: Optional[str] = Field(None, description='Unique identifier for the ticket')
    name: Optional[str] = Field(None, description='Name of the ticket')
    name_on_ticket: Optional[str] = Field(
        None, description='Name to be printed on the ticket'
    )
    customer_email: Optional[str] = Field(
        None, description='Email of the customer who owns the ticket'
    )
    created_at: Optional[datetime] = Field(
        None, description='Timestamp when the ticket was created'
    )
    updated_at: Optional[datetime] = Field(
        None, description='Timestamp when the ticket was last updated'
    )
    includes: Optional[List[str]] = Field(
        None, description='List of items included with the ticket'
    )
    expanded_includes: Optional[List[Dict[str, Any]]] = Field(
        None, description='List of the items included with the ticket'
    )
    creation_idempotency: Optional[Dict[str, Any]] = Field(
        None, description='Idempotency record for the ticket creation request'
    )


class TicketListResponse(BaseModel):
    tickets: Optional[List[TicketObject]] = None


class SendTicketEmailRequest(BaseModel):
    tickets: List[str]


class LineItem(BaseModel):
    ksuid: str
    entity_type: str
    name: str
    includes: Optional[List[str]] = None


class Ticket(BaseModel):
    customer_email: str
    name_on_ticket: str
    ticket_creation_key: Optional[str] = None
    line_items: List[LineItem]


class BulkImportTicketsRequest(BaseModel):
    preview: Optional[bool] = Field(
        None,
        description='When true, return the tickets that would be created without creating them.',
    )
    tickets: List[Ticket]