# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-02-21T20:44:38+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class TicketObject(BaseModel):
    ksuid: Optional[str] = Field(None, description='Unique identifier for the ticket')
    name: Optional[str] = Field(None, description='Name of the ticket')
    name_on_ticket: Optional[str] = Field(
        None, description='Name to be printed on the ticket'
    )
    customer_email: Optional[str] = Field(
        None, description='Email of the customer who owns the ticket'
    )
    created_at: Optional[datetime] = Field(
        None, description='Timestamp when the ticket was created'
    )
    updated_at: Optional[datetime] = Field(
        None, description='Timestamp when the ticket was last updated'
    )
    includes: Optional[List[str]] = Field(
        None, description='List of items included with the ticket'
    )


class TicketListResponse(BaseModel):
    tickets: Optional[List[TicketObject]] = None
