# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-06-27T18:08:06+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Status(Enum):
    active = 'active'
    setup = 'setup'
    suspended = 'suspended'
    archived = 'archived'


class OrganisationObject(BaseModel):
    status: Optional[Status] = 'draft'
    ksuid: Optional[str] = Field(None, description='ID of the organisation')
    entity_type: Optional[str] = None
    name: str = Field(..., description='The name of the organisation.', min_length=2)
    description: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    version: Optional[int] = None
    history: Optional[List[Dict[str, Any]]] = None


class OrganisationResponse(BaseModel):
    organisation: Optional[OrganisationObject] = None


class UpdateOrganisationRequest(BaseModel):
    organisation: OrganisationObject
